### ISSUE TITLE
Write about LEAN

### ISSUE THREAD

**Issue by Futsy** [stil4m/software-process#22]
Write the part about LEAN - both for RUP > Scrum and Scrum > RUP as in WASTE.

**Comment by Futsy** [comment]
I'll start with this 16-02-2016 (Night).

**Comment by OlavTrauschke** [comment]
@Futsy where can I find this document to review it? I can't find it on our Google Drive directory.

**Comment by Futsy** [comment]
@OlavTrauschke Software Process > Weeks3-4 > LEAN > Lean

**Comment by OlavTrauschke** [comment]
@Futsy Drive was screwing things up yesterday. I asked this because there was nothing in the LEAN folder, but now it's there...
